### ISSUE TITLE
Incorrect Branch causing all match modes (except GAPMM) to return the same value

### ISSUE THREAD

**Issue by AABoyles** [sdwfrost/libtn93#3]
I was looking over your source while doing some optimizations on my Javascript port (trying to stay competitive! 😉). My version had a branch that caused all match modes except GAPMM to return the same value, regardless of the presence or distribution of gaps. I believe [yours has it too](https://github.com/sdwfrost/libtn93/blob/master/src/tn93.c#L339) (and the [original does as well](https://github.com/veg/tn93/issues/13)). I'm sorry I don't have the resources to patch it myself, but if true, this could be a critical bug and I thought you should know about it.

**Comment by AABoyles** [comment]
Actually, please disregard this. I misunderstood the purpose of that region of the code.

**Comment by sdwfrost** [comment]
No problem. Have you optimised? My notebooks seem to say so...
